language: go
go:
  - 1.12.x
  - master

before_install:
   - go get github.com/gorilla/mux
   - go get github.com/stretchr/testify/assert

install: true

jobs:
  include:
    - stage: calculator
      before_script: cd src/calculator
      script:
        - go build
        - go test -v -coverprofile=coverage_calculator.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: api
      before_script: cd src/api
      script:
        - go build
        - go test -v -coverprofile=coverage_api.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - stage: apimux
      before_script: cd src/apimux
      script:
        - go build
        - go test -v -coverprofile=coverage_apimux.txt -covermode=atomic
      after_success:
        - bash <(curl -s https://codecov.io/bash)        